default:
  tags:
    - docker-ci


stages:
  - static-test
  - build
  - integration-test
  - deploy

.scriptDebug: &scriptDebug
    - echo "CI_JOB_NAME >>> ${CI_JOB_NAME}"
    - echo "CI_JOB_STAGE >>> ${CI_JOB_STAGE}"


static-test: &test
  stage: static-test
  image: harbor.k8sd-hom.prevnet/mirror/golang:1.20.3-build-rdb
  
  script:
    - cd src
    - go test ./... -skip Integration
  only:
    - develop
    - /^feature-.*$/

build:
  stage: build
  script: *scriptDebug
  only:
    - develop

integration-test:
  <<: *test
  stage: integration-test
  script:
    - cd src
    - go test ./... -run _test_integration\.go$
  only:
    - develop

deploy:
  stage: deploy
  script: *scriptDebug
  environment:
    name: develop
  only:
    - develop
