default:
  tags:
    - docker-ci


stages:
  - static-test
  - build
  - integration-test
  - release
  - deploy

.scriptDebug: &scriptDebug
    - echo "CI_JOB_NAME >>> ${CI_JOB_NAME}"
    - echo "CI_JOB_STAGE >>> ${CI_JOB_STAGE}"
    - echo "CI_COMMIT_REF_SLUG >>> ${CI_COMMIT_REF_SLUG}"

static-test: &test
  stage: static-test
  image: harbor.k8sd-hom.prevnet/mirror/golang:1.20.3-build-rdb
  
  script:
    - *scriptDebug
    - cd src
    - go test ./... -skip Integration
  only:
    - develop
    - /^feature-.*$/
    - /^release-.*$/

build:
  stage: build
  script: *scriptDebug
  only:
    - develop

integration-test:
  <<: *test
  stage: integration-test
  script:
    - cd src
    - go test ./... -run _test_integration\.go$
  only:
    - develop

deploy-dev: &deploy
  stage: deploy
  script: *scriptDebug
  environment:
    name: develop
  only:
    - develop

release-test: &deploy
  <<: *test
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.rdb.k8sd.hom.df.cloud.dataprev.gov.br
  stage: release
  script: *scriptDebug
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}/contagem
  only:
    - /^release-.*$/
