default:
  tags:
    - docker-ci

stages:
  - static-test
  - build
  - deploy
  - integration-test
  - release

.scriptDebug: &scriptDebug
    - echo "CI_JOB_NAME >>> ${CI_JOB_NAME}"
    - echo "CI_JOB_STAGE >>> ${CI_JOB_STAGE}"
    - echo "CI_COMMIT_REF_SLUG >>> ${CI_COMMIT_REF_SLUG}"

static-test: &test
  stage: static-test
  image: harbor.k8sd-hom.prevnet/mirror/golang:1.20.3-build-rdb
  
  script:
    - *scriptDebug
    - cd src
    - go test ./... -skip Integration
  only:
    - develop
    - /^feature-.*$/
    - /^release-.*$/

build:
  stage: build
  script: *scriptDebug
  only:
    - develop

deploy-dev: &deploy
  variables:
    CNAME: dev-rdb.k8sd.hom.df.cloud.dataprev.gov.br
  stage: deploy
  script: *scriptDebug
  environment:
    name: develop
  only:
    - develop

integration-test:
  <<: *test
  stage: integration-test
  script:
    - cd src
    - go test ./... -run Integration
  only:
    - staging

release-test: &deploy
  <<: *test
  variables:
    CNAME: $CI_COMMIT_REF_SLUG-rdb.k8sd.hom.df.cloud.dataprev.gov.br
    GIT_STRATEGY: none
  stage: release
  script: *scriptDebug
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}/contagem
    on_stop: turnoff-environemnt
  only:
    - /^release-.*$/

turnoff-environemnt:
  <<: *deploy
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}/contagem
    action: stop
