version: "3.7"

services:
  app:
    container_name: app01
    image: go-rt-dev:1.20.3
    volumes:
      - ./src:/app
  #   env_file: .env.docker
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true      
  #   command: bash -c "sleep infinity"
  # db:
  #   container_name: binodb
  #   image: mysql:8
  #   restart: always
  #   env_file: .env.docker
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d
  #   ports:
  #     - 0.0.0.0:3306:3306
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20
  #     start_period: 15s
  
