version: "3.7"

services:
  app:
    container_name: app01
    image: go-rt-dev:1.20.3
    volumes:
      - ./src:/app
  #   env_file: .env.docker
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true      
  #   command: bash -c "sleep infinity"
  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123Mudar
      POSTGRES_DB: rinha-de-backend
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    # network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
  
